In [12]:
import numpy as np
import pandas as pd

In [11]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
display(np.shape(arr1))

(3, 3)

In [13]:
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [14]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
display(my_series.values)

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [24]:
a = np.random.randint(0, 10, (3, 3))
display(a)

array([[7, 6, 1],
       [3, 9, 4],
       [9, 3, 2]])

In [29]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
display(big_secret)

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [28]:
display(sum(big_secret[4]))

12750.0

In [59]:
bs = big_secret[:,:5]
display(bs[0,0]+bs[1,1]+bs[2,2]+bs[3,3]+bs[4,4])

121.37188663699624

In [64]:
bs2 = big_secret[:,-5:]
display(bs2[0,0]*bs2[1,1]*bs2[2,2]*bs2[3,3]*bs2[4,4])

341505315559.2347

In [65]:
my_array = np.random.randint(1, 100, (4, 6))
display(my_array)

array([[ 6, 69,  5, 96, 26, 87],
       [20, 36,  2, 60, 56, 50],
       [88, 62, 25, 18, 88, 70],
       [51,  4, 10, 31, 83, 31]])

In [66]:
my_slice = my_array[1:3, 2:4]
display(my_slice)

array([[ 2, 60],
       [25, 18]])

In [67]:
my_slice[:] = 0
display(my_array)

array([[ 6, 69,  5, 96, 26, 87],
       [20, 36,  0,  0, 56, 50],
       [88, 62,  0,  0, 88, 70],
       [51,  4, 10, 31, 83, 31]])

In [71]:
for i in range(len(big_secret)):
    for j in range(len(big_secret[i])):
        if i % 2 == 0 and j % 2 == 0:
            big_secret[i, j] = -1
        elif i % 2 == 1 and j % 2 == 1:
            big_secret[i, j] = 1
bs3 = big_secret[:, :5]
display(bs3[0,0]+bs3[1,1]+bs3[2,2]+bs3[3,3]+bs3[4,4])

-1.0

In [72]:
bs4 = big_secret[:,-5:]
display(bs4)
display(bs4[0,0]*bs4[1,1]*bs4[2,2]*bs4[3,3]*bs4[4,4])

array([[-1.00000000e+00,  2.76000000e+02, -1.00000000e+00,
         4.90000000e+02, -1.00000000e+00],
       [ 3.30454233e+01,  1.00000000e+00,  3.31058907e+01,
         1.00000000e+00,  3.31662479e+01],
       [-1.00000000e+00,  2.20900000e+03, -1.00000000e+00,
         2.40100000e+03, -1.00000000e+00],
       [ 3.30454233e+01,  1.00000000e+00,  3.31058907e+01,
         1.00000000e+00,  3.31662479e+01],
       [-1.00000000e+00,  2.76000000e+02, -1.00000000e+00,
         4.90000000e+02, -1.00000000e+00]])

-1.0

In [73]:
a = np.array([3,6,9])
b = np.array([12,15,18])
display(a)
display(b)

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

array([3, 6, 9])

array([12, 15, 18])

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [74]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
display(my_array)
display(my_array.T)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [75]:
my_array = np.random.randint(0, 10, 20)
display(my_array)
display(my_array.reshape((4,5)))

array([2, 3, 0, 2, 4, 6, 8, 8, 6, 5, 2, 9, 7, 7, 6, 0, 6, 7, 8, 5])

array([[2, 3, 0, 2, 4],
       [6, 8, 8, 6, 5],
       [2, 9, 7, 7, 6],
       [0, 6, 7, 8, 5]])

In [76]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
display(my_array)
display(my_array.flatten())

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [78]:
my_array = np.random.randint(0, 10, (3,4))

array([[False,  True, False, False],
       [ True, False,  True,  True],
       [ True, False,  True, False]])

In [81]:
display(my_array)
display(my_array[my_array<5])

array([[6, 1, 9, 9],
       [4, 9, 1, 0],
       [2, 8, 1, 7]])

array([1, 4, 1, 0, 2, 1])

In [82]:
mask = np.array([1, 0, 1, 0], dtype=bool)
display(my_array[:, mask])

array([[6, 9],
       [4, 1],
       [2, 1]])

In [83]:
my_array = np.random.randint(0, 10, (4, 6))
display(my_array)

display(np.sort(my_array, axis=1))

display(np.sort(my_array, axis=0))

array([[8, 2, 1, 5, 4, 6],
       [5, 1, 7, 8, 9, 5],
       [5, 5, 3, 3, 1, 7],
       [0, 7, 1, 2, 7, 2]])

array([[1, 2, 4, 5, 6, 8],
       [1, 5, 5, 7, 8, 9],
       [1, 3, 3, 5, 5, 7],
       [0, 1, 2, 2, 7, 7]])

array([[0, 1, 1, 2, 1, 2],
       [5, 2, 1, 3, 4, 5],
       [5, 5, 3, 5, 7, 6],
       [8, 7, 7, 8, 9, 7]])

In [84]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
display(great_secret)

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

In [87]:
elem0 = great_secret[0]
display(sum(np.cos(elem0)))

0.16006721889793019

In [88]:
display(sum(great_secret[great_secret > 50]))

5470.0

In [91]:
display(great_secret.flatten()[150])

7.0710678118654755

In [94]:
display(sum(np.sort(great_secret, axis=1)[-1]))

75.3881468318802

In [95]:
students = np.array([[1, 135, 34, 4],
                   [2, 160, 43, 5],
                   [3, 163, 40, 4.3],
                   [4, 147, 44, 5],
                   [5, 138, 41, 4.7],
                   [6, 149, 54, 3.9],
                   [7, 136, 39, 4.2],
                   [8, 154, 48, 4.9],
                   [9, 137, 35, 3.7],
                   [10, 165, 60, 4.6]])
display(students)

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [98]:
mean = np.mean(students[:,-1])
display(mean)

4.430000000000001

In [99]:
median = np.median(students[:,-1])
display(median)

4.449999999999999

In [101]:
sort = np.sort(students[:,-1])
display(sort)
display((sort[4]+sort[5])/2)

array([3.7, 3.9, 4. , 4.2, 4.3, 4.6, 4.7, 4.9, 5. , 5. ])

4.449999999999999

In [102]:
median_mass = np.median(students[:, -2])
display(median_mass)

42.0

In [103]:
display(np.mean(students[:, -2]) - median_mass)

1.7999999999999972

In [107]:
corr = np.corrcoef(students[:,1], students[:,2])
display(corr)
corr2 = np.corrcoef(students[:,1], students[:, -1])
display(corr2)
corr3 = np.corrcoef(students[:,2], students[:,-1])
display(corr3)

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [108]:
std = np.std(students[:, 1])
display(std)

11.083320801997928

In [109]:
std2 = np.std(students[:, -1])
display(std2)

0.4517742799230607

In [113]:
disp = np.var(students[:, 2])
display(disp)
disp1 = np.std(students[:,2])**2
display(disp1)

60.36

60.36

In [120]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_slice = np.array(my_array[1:4, 1:4])
display(my_slice)

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [123]:
my_sin = np.sin(my_array)
display(sum(sum(my_sin)))

-0.05812430261413326

In [126]:
my_sin[1:4, 1:4] = 1
display(sum(sum(my_sin)))

7.571718421269144

In [131]:
arr01 = my_sin[:, :4].flatten().reshape(10, 2)
display(sum(arr01[:, 0]))

2.4057172058139544

In [134]:
bigdata = np.array([x**2 for x in range(101, 1000, 2)])
display(np.median(bigdata))
display(np.std(bigdata))

302501.0

292095.0301991155

In [136]:
corr01 = np.corrcoef(bigdata[::2], bigdata[1::2])
display(corr01)

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])